apiVersion: v1
kind: Secret
metadata:
  name: node-app-website-secret
type: Opaque
stringData:
  DB_HOST: mysql.default.svc.cluster.local
  DB_USER: app_user
  DB_PASSWORD: app_password_123
  API_KEY: sample_api_key_abc123